image: Visual Studio 2017

init:
  - cmd: set
  - cmd: node --version

install:
  # Get the correct version of Node.js (will also uninstall 8.11.1 x86)
  - ps: Install-Product node 6.10.1 x64
  - cmd: node --version
  - npm install -g ./Alarm/dzn-2.7.0.tar.gz
  - cd %APPVEYOR_BUILD_FOLDER%
  - Alarm\Build.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - Tests\Build.bat
  
# run tests
  - cd %APPVEYOR_BUILD_FOLDER%\Tests\Release
  - cd
  - dir
  - Tests.exe -s -i -w NoTests -r junit -o junit-results.xml
  - ps: Tests\UploadTestResults.ps1

artifacts:
  - path: Alarm\build.txt
    name: buildresult
    
# switch to disable automatic builds (outside/after this script)
# set to 'off' in case you trigger your build explicitly from this script
build: off