image: Visual Studio 2017

init:
  - cmd: set
  - cmd: node --version

install:
  # Get the correct version of Node.js (will also uninstall 8.11.1 x86)
  - ps: Install-Product node 6.10.1 x64
  - cmd: node --version
  - npm install -g ./Alarm/dzn-2.7.0.tar.gz
  - cd %APPVEYOR_BUILD_FOLDER%
#  - Alarm\Build.bat
  - BuildTests.bat
  
# run tests
  - ps RunTests.ps
  
# switch to disable automatic builds (outside/after this script)
# set to 'off' in case you trigger your build explicitly from this script
build: off