image: Visual Studio 2013

init:
  - cmd: set
  - cmd: node --version

install:
  # Get the correct version of Node.js (will also uninstall 8.11.1 x86)
  - ps: Install-Product node 6.10.1 x64
  - cmd: node --version
  - npm install -g ./Alarm/dzn-2.7.0.tar.gz
  - pushd 
  - Alarm\DezyneGenerateCode.bat
  - popd
  
test_script:
  - Alarm\build.bat
    
# to disable automatic builds (outside/after this script)
build: off