image: Visual Studio 2013

install:
  # Get the version of Node.js 
  - ps: Install-Product node 6.10.1 x64
  - npm install -g dzn-2.7.0.tar.gz
  
test_script:
  - cmd: ECHO this is batch
  - cmd: node --version
  - cmd: Alarm\DezyneGenerateCode.bat
  - cmd: msbuild Alarm\vs2017project\Alarm.sln
    